//The JS communicates with the C++ trough an object called _launcher that is gonna be generated by the C++
var _proxy; //The C++ communicates with the JS trough this object
var launcherWeb; //This object contains all the web local launcher logic

function ClientProxy() {
}

$.extend(ClientProxy.prototype, {
    _triggerHideLaunchButton: function() { $(this).trigger('hideLaunchButton'); },
    _triggerLoadLoginPage: function(params) { $(this).trigger('loadLoginPage', params); },
    _triggerHideProgressionBar: function() { $(this).trigger('hideProgressbar'); },
    _triggerShowMessageBox: function(options) { $(this).trigger('showMessageBox', options); },
    _triggerProgressionChange: function(progression) { $(this).trigger('progressionChange', progression); },
    _triggerShowLaunchButton: function() { $(this).trigger('showLaunchButton'); },
    _triggerShowProgressionBar: function() { $(this).trigger('showProgressbar'); },
    _triggerVersionNumberChange: function(version) { $(this).trigger('versionNumberChange', version); },
    submitFormWithSteamTicket: function(steamTicket) { launcherWeb.submitFormWithSteamTicket(steamTicket); }
});

function LauncherWeb(proxy) {
    this.proxy = proxy;

    LauncherWeb.log("init");
    this.initProgressbar();
    this.initMessageBox();
    this.bindProxy();
    this.bindButtons();
    this.bindRemotePagesIFrame();
    this.initMaintenanceMessages();
}

$.extend(LauncherWeb.prototype, {

    REMOTE_LANG_COOKIE: "launcher_locale",
    REMOTE_USER_EMAIL_COOKIE: "email",
    LAUNCH_BUTTON_WITH_AVAILABLE_ADVERTISED_PACK_TRANSLATION_KEY: 48,
    MAINTENANCE_TITLE_TRANSLATION_KEY: 51,
    MAINTENANCE_SUBTITLE_TRANSLATION_KEY: 52,
    ADVERTISED_PACK_BUTTON_TRANSLATION_KEY: 53,
    LAUNCH_BUTTON_WITHOUT_AVAILABLE_ADVERTISED_PACK_TRANSLATION_KEY: 54,
    _version: {TextID: null, TextParams: null},
    inPurchaseMode: false,
    loginPageURL: '',

    initProgressbar: function() {
        $( "#progressbar" ).progressbar();
    },

    initMessageBox: function() {
        this.$messageBox = $('<div id="message-box"></div>');
        this.$messageBox.dialog({
            autoOpen: false,
            closeOnEscape: false,
            open: this._hideMessageBoxCloseButton
        });
    },

    initMaintenanceMessages: function() {
        $('#maintenance-title').text(I18n.translate(this.MAINTENANCE_TITLE_TRANSLATION_KEY));
        $('#maintenance-subtitle').text(I18n.translate(this.MAINTENANCE_SUBTITLE_TRANSLATION_KEY));
    },

    bindAdvertisedPackButton: function () {
        var launcher = this;
        $("#advertised-pack-button").click(function () {
            launcher.inPurchaseMode = true;
            return true;
        });
    },

    forceUserToAutoSignInAgain: function (launcher) {
        // Delete t cookie that contains game token to force a new login on the server
        launcher._getRemoteWindow().document.cookie = 't=; expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/';

        var now = new Date();
        var maximumAllowedExpiration = 30000; // This is 30 seconds
        now.setTime(now.getTime() + maximumAllowedExpiration);
        launcher._getRemoteWindow().document.cookie = 'force_auto_sign_in=true; expires='+now.toGMTString()+';path=/';

        $('body').hide();
        $('#remote-launcher-pages').hide().attr('src', launcher.loginPageURL);
    },

    autoSignInUserAgainToRedeemPreviousPurchases: function (launcher) {
        $('#remote-launcher-pages').load(function () {
            _launcher._onUserLoggedIn(JSON.stringify(
                launcher._buildUserInfoPayload()
            ));
            launcher.launchGame();
        });
        this.forceUserToAutoSignInAgain(launcher);
    },

    inSteamContext: function () {
        if (this.loginPageURL.indexOf('?') != -1) {
            var queryString = this.loginPageURL.split('?')[1];
            if (queryString != 'undefined' && queryString.indexOf('steamID') != -1) {
                return true;
            }
        }
        return false;
    },

    bindLaunchButton: function () {
        var launcher = this;
        $("#launch-button").click(function () {
            if (launcher.inPurchaseMode && launcher.inSteamContext()) {
                launcher.autoSignInUserAgainToRedeemPreviousPurchases(launcher);
            } else {
                launcher.launchGame();
            }
        });
    },

    bindButtons: function() {
        $("#close-launcher-button").click(this.exitApplication);
        $("#debug-launcher-button").click(function(){
            _proxy._triggerShowLaunchButton();
            _proxy._triggerShowMessageBox({
                "TitleTextID": "4",
                "InfoTextID": "12",
                "TextParams": [],
                "ButtonTextIDs": ['14']});
            setInterval(LauncherWeb.setRandomProgress,500);
        });
        this.bindAdvertisedPackButton();
        this.bindLaunchButton();
    },


    bindProxy: function () {
        $(this.proxy).on({
            hideLaunchButton: $.proxy(this.hideLaunchButton, this),
            hideProgressbar: $.proxy(this.hideProgressbar, this),
            loadLoginPage: $.proxy(this.loadLoginPage, this),
            progressionChange: $.proxy(this.progressionChange, this),
            showLaunchButton: $.proxy(this.showLaunchButton, this),
            showMessageBox: $.proxy(this.showMessageBox, this),
            showProgressbar: $.proxy(this.showProgressbar, this),
            versionNumberChange: $.proxy(this.versionNumberChange, this)
        });
    },

    bindRemotePagesIFrame: function () {
        $('#remote-launcher-pages')
            .load(function() { $(this).show(); })
            .load($.proxy(this._setupLauncher, this));
    },

    exitApplication: function() {
        LauncherWeb.log("_triggerExitApplication");
        _launcher._triggerExitApplication('');
    },

    launchGame: function() {
        if ($("#launch-button").hasClass('disabled')) { return; }
        LauncherWeb.log("_onLaunchButtonClicked");
        _launcher._onLaunchButtonClicked('');
    },

    hideLaunchButton: function (event) {
        LauncherWeb.log("hideLaunchButton");
        $('#launch-button').hide();
        this._hideAdvertisedPackButton();
    },

    hideProgressbar:function (event) {
        LauncherWeb.log("hideProgressBar");
        $('#progressbar').hide();
    },

    loadLoginPage: function(event, params){
        LauncherWeb.log('loadLoginPage');
        LauncherWeb.log('Received login page URL from C++: ' + params.LoginPageUrl);
        LauncherWeb.log('Received language from C++: ' + params.Language);

        this._setLanguage(params.Language);

        launcherWeb.loginPageURL = this._buildLocalizedURL(params);

        $('#remote-launcher-pages').hide().attr('src', launcherWeb.loginPageURL);
        LauncherWeb.log('Build URL set in iframe: ' + launcherWeb.loginPageURL);

        this._addSteamTicketUpdateListeners();
    },

    progressionChange:function (event, progression) {
        $('#progressbar').progressbar('value', progression.Progress);
        $('#progression-text').html(I18n.translate(progression.TextID, progression.TextParams));
    },

    showLaunchButton:function (event) {
        LauncherWeb.log("showLaunchButton");
        $('#launch-button').show().removeClass('disabled');
        if (this._advertisedPackAvailable()) { this._showAdvertisedPackButton(); }
    },

    _addSteamTicketUpdateListeners: function() {
        LauncherWeb.log('_addSteamTicketUpdateListeners');
        $('#remote-launcher-pages').load(function() {
            $(this).contents().on('submit', 'form', launcherWeb._steamTicketUpdateHandler);
        });
    },

    _steamTicketUpdateHandler: function(event) {
        launcherWeb._updateSteamTicket();
        event.preventDefault();
    },

    _updateSteamTicket: function() {
        LauncherWeb.log('_updateSteamTicket');
        var callback_function = 'submitFormWithSteamTicket';
        _launcher._updateSteamToken(callback_function);
    },

    submitFormWithSteamTicket: function(steamTicket) {
        LauncherWeb.log('submitFormWithSteamTicket: ' + steamTicket);

        $('#remote-launcher-pages').contents().off('submit', 'form', launcherWeb._steamTicketUpdateHandler);
        this._formWithSteamTicket(steamTicket).submit();
        $('#remote-launcher-pages').contents().on('submit', 'form', launcherWeb._steamTicketUpdateHandler);
    },

    _formWithSteamTicket: function(steamTicket) {
        var form = $('#remote-launcher-pages').contents().find('form');
        form.append('<input type="hidden" name="steam_ticket" value="' + steamTicket + '">');
        return form;
    },

    showMessageBox:function (event, options) {
        LauncherWeb.log('showMessageBox');

        var self = this;
        var buttons = {};
        var textParams = options.TextParams;

        $.each(options.ButtonTextIDs, function(buttonIndex, buttonTextID) {
            var buttonText =  I18n.translate(buttonTextID, textParams);
            buttons[buttonText] = function() { self._closeDialogFunction(buttonIndex); };
        });

        this.$messageBox.html(I18n.translate(options.InfoTextID, options.TextParams));
        this.$messageBox.dialog('option', {
            "title": I18n.translate(options.TitleTextID, options.TextParams),
            "buttons": buttons
        });

        this.$messageBox.dialog('open');
    },

    showProgressbar:function (event) {
        LauncherWeb.log("showProgressBar");
        $('#progressbar').show();
    },

    versionNumberChange:function (event, version) {
        LauncherWeb.log("versionNumberChange");
        LauncherWeb.log(I18n.translate(version.TextID));
        this._version = version;
        this._updateVersionLabel();
    },

    _showAdvertisedPackButton: function (event) {
        this._shiftLaunchButton('right', '195px');
        $('#advertised-pack-button').show();
    },

    _hideAdvertisedPackButton: function (event) {
        this._shiftLaunchButton('right', '100px');
        $('#advertised-pack-button').hide();
    },

    _setAdvertisedPackButtonUrl: function() {
        var url = this._getRemoteCookie('advertised_pack_url');
        if (url === undefined) { return; }
        $('#advertised-pack-button').attr('href', unescape(url).replace('+', '%2D'));
    },

    _shiftLaunchButton: function(direction, distance) {
        $('#launch-button').css(direction, distance);
    },

    _setupLauncher: function() {
        $('#logo').hide();
        this._setAdvertisedPackButtonUrl();
        this._detectLogin();
        this._detectLocale();
    },

    _detectLogin: function () {
        var userLoggedInAndHasGameToken = this._userIsLoggedInAndHasGameToken();
        if (!this.clientLauncherCurrentlyLoggedIn && userLoggedInAndHasGameToken){
            LauncherWeb.log("Logged in");
            this.clientLauncherCurrentlyLoggedIn = true;
            $('#launch-button').show().addClass('disabled');
            if (this._advertisedPackAvailable()) { this._showAdvertisedPackButton(); }
            _launcher._onUserLoggedIn(JSON.stringify(
                this._buildUserInfoPayload()
            ));
        } else if (!userLoggedInAndHasGameToken){
            LauncherWeb.log("Logged out");
            this.clientLauncherCurrentlyLoggedIn = false;
            _launcher._onUserLoggedOut("");
        }
    },

    _buildUserInfoPayload: function() {
        var gameToken = this._getRemoteCookie("t");
        var sessionID = this._getRemoteCookie("hyperquest_launcher_session");
        var userEmail = this._getRemoteCookie(this.REMOTE_USER_EMAIL_COOKIE);

        return {
            LoginToken: gameToken,
            SGToken: sessionID,
            UserEmail: userEmail
        };
    },

    _detectLocale: function () {
        var locale = this._getRemoteCookie(this.REMOTE_LANG_COOKIE);
        this._setLanguage(locale);
        this._updateLocalContent();
        _launcher._onUserSelectLanguage(locale);
    },

    _updateVersionLabel: function() {
        $('.version-label').html(I18n.translate(this._version.TextID, this._version.TextParams));
    },

    _updateButtonsText: function() {
        var launch_button = $('#launch-button');

        var launch_button_text = I18n.translate(this.LAUNCH_BUTTON_WITHOUT_AVAILABLE_ADVERTISED_PACK_TRANSLATION_KEY);
        launch_button.addClass('no-advertised-pack-available');

        if (this._advertisedPackAvailable()) {
            launch_button_text = I18n.translate(this.LAUNCH_BUTTON_WITH_AVAILABLE_ADVERTISED_PACK_TRANSLATION_KEY);
            launch_button.removeClass('no-advertised-pack-available');
        }

        launch_button.html(launch_button_text);
        $('#advertised-pack-button div').text(I18n.translate(this.ADVERTISED_PACK_BUTTON_TRANSLATION_KEY));
    },

    _advertisedPackAvailable: function() {
        var advertisedPackButtonHref = $('#advertised-pack-button').attr('href');
        return advertisedPackButtonHref !== undefined;
    },

    _updateButtonsLanguageClass: function() {
        this._removeButtonsLanguageClasses();
        $('#launch-button').addClass(I18n.currentLanguage);
        $('#advertised-pack-button').addClass(I18n.currentLanguage);
    },

    _removeButtonsLanguageClasses: function() {
        $('#launch-button').removeClass('fr en de pl pt ru');
        $('#advertised-pack-button').removeClass('fr en de pl pt ru');
    },

    _updateLocalContent: function() {
        LauncherWeb.log('_updateLocalContent');
        this._updateVersionLabel();
        this._updateButtonsText();
        this._updateButtonsLanguageClass();
    },

    _closeDialogFunction: function(buttonIndex) {
        this.$messageBox.dialog("close");
        _launcher._onMessageBoxDismissedWithSelection(String(buttonIndex));
    },

    _getRemoteWindow: function() {
        return $('#remote-launcher-pages').get(0).contentWindow;
    },

    _getLanguageRollback: function(lang) {
        return I18n.hasLanguage(lang) ? lang : I18n.defaultLanguage;
    },

    _setLanguage: function(lang) {
        I18n.currentLanguage = this._getLanguageRollback(lang);
    },

    _isLoggedInRemoteLauncher: function() {
        return this._getRemoteWindow().userIsLoggedIn;
    },

    _fetchRemoteCookies: function() {
        return this._getRemoteWindow().document.cookie;
    },

    _extractCookie: function(cookieString, cookieName) {
        var token;
        var regex = new RegExp('(?:^|;)\\s?' + cookieName + '=(.*?)(?:;|$)','i');
        match = cookieString.match(regex);
        if (match !== null && match.length === 2){
            token = match[1];
        }
        return token;
    },

    _buildLocalizedURL: function(params) {
        if (!params.Language) { return params.LoginPageUrl; }

        urlHasAQueryString = params.LoginPageUrl.indexOf('?') !== -1;
        localeParameterCharacter = urlHasAQueryString ? '&' : '?';
        return params.LoginPageUrl + localeParameterCharacter + "locale=" + this._getLanguageRollback(params.Language);
    },

    _getRemoteCookie: function(cookieName) {
        var cookieString = this._fetchRemoteCookies();
        return this._extractCookie(cookieString, cookieName);
    },

    _userIsLoggedInAndHasGameToken : function() {
        var gameToken = this._getRemoteCookie("t");
        return this._isLoggedInRemoteLauncher() && gameToken;
    },

    _hideMessageBoxCloseButton: function(event, ui) {
        $(this).parent().children().children('.ui-dialog-titlebar-close').hide();
    }

});

LauncherWeb.log = function (message) {
    console.log(message);
    if (typeof(_launcher) !== "undefined"){
        _launcher._triggerLog(message);
    }
};

LauncherWeb.setRandomProgress = function() {
    var progress = Math.floor(Math.random()*101);
    var message = Math.floor(Math.random()*20);
    _proxy._triggerShowProgressionBar();
    _proxy._triggerProgressionChange({"Progress": progress,"TextID": message,"TextParams":[]});
};

logMissingTranslation = function(key, currentLanguage) {
    LauncherWeb.log("Missing translation for: [KEY] => " + key + ", [LANG] => " + currentLanguage);
};

$(function() {
    I18n.currentLanguage = 'en';
    I18n.bind("missingTranslation", logMissingTranslation);
    _proxy = new ClientProxy();
    launcherWeb = new LauncherWeb(_proxy);
});